# Generated by Django 6.0.3 on 2026-03-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
